name: Infra Pipeline - CloudFormation

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy VPC Stack
        run: |
          aws cloudformation deploy \
            --template-file infra-pipeline/cloudformation/vpc.yml \
            --stack-name devops-vpc-stack \
            --region us-east-1

      - name: Deploy IAM Stack
        run: |
          aws cloudformation deploy \
            --template-file infra-pipeline/cloudformation/iam.yml \
            --stack-name devops-iam-stack \
            --region us-east-1 \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy EC2 Stack
        run: |
          aws cloudformation deploy \
            --template-file infra-pipeline/cloudformation/ec2.yml \
            --stack-name devops-ec2-stack \
            --region us-east-1 \
            --parameter-overrides KeyName=devops-key

      - name: Deploy EKS Stack
        run: |
          aws cloudformation deploy \
            --template-file infra-pipeline/cloudformation/eks.yml \
            --stack-name devops-eks-stack \
            --region us-east-1 \
            --capabilities CAPABILITY_NAMED_IAM
